export const FIND_ALL_CATEGORIES_COMPLETED = 'FIND_ALL_CATEGORIES_COMPLETED';
export const FIND_PRODUCTS_COMPLETED = 'FIND_PRODUCTS_COMPLETED';
export const CLEAR_PRODUCT_SEARCH = 'CLEAR_PRODUCT_SEARCH';
export const FIND_PRODUCT_BY_ID_COMPLETED = 'FIND_PRODUCT_BY_ID_COMPLETED';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

export const FETCH_NEWLY_ADDED_PRODUCTS_SUCCESS = 'FETCH_NEWLY_ADDED_PRODUCTS_SUCCESS';
export const FETCH_NEWLY_ADDED_PRODUCTS_REQUEST = 'FETCH_NEWLY_ADDED_PRODUCTS_REQUEST';
export const FETCH_NEWLY_ADDED_PRODUCTS_FAILURE = 'FETCH_NEWLY_ADDED_PRODUCTS_FAILURE';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';